package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="ardetails")
public class Ardetails {
  @javax.persistence.Id
  //@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  //@javax.persistence.Column(name="id",length=19,nullable=false)
  @javax.persistence.GeneratedValue
  @javax.persistence.Column(name="id")
  private long id;

  public void setId(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  @javax.persistence.Column(name="ItemCode",length=30)
  private String itemcode;

  public void setItemcode(String itemcode) {
    this.itemcode = itemcode;
  }

  public String getItemcode() {
    return itemcode;
  }

  @javax.persistence.Column(name="InvoiceNumber",length=20,nullable=false)
  private String invoicenumber = "";

  public void setInvoicenumber(String ordernumber) {
    this.invoicenumber = ordernumber;
  }

  public String getInvoicenumber() {
    return invoicenumber;
  }

  @javax.persistence.Column(name="PriceEntered",length=12)
  private Float priceentered;

  public void setPriceentered(Float priceentered) {
    this.priceentered = priceentered;
  }

  public Float getPriceentered() {
    return priceentered;
  }

  @javax.persistence.Column(name="Quantity",length=10)
  private Integer quantity;

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public Integer getQuantity() {
    return quantity;
  }

  @javax.persistence.Column(name="Tax",length=12)
  private Float tax;

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public Float getTax() {
    return tax;
  }
// <- Generated by DB Importer
}