package com.oes.model.my_sql.entities;

import org.apache.commons.lang.StringUtils;


// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="aropen")
public class Aropen {
	@javax.persistence.Id
	//@org.hibernate.annotations.GenericGenerator(name="generator", strategy="increment" )
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
	//@javax.persistence.GeneratedValue(generator="generator")
	@javax.persistence.Column(name="ID",length=19,nullable=false)
	private long id;

	public void setId(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	@javax.persistence.Column(name="Balance",length=12)
	private double balance;

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public double getBalance() {
		return balance;
	}

	@javax.persistence.Column(name="CustomerPO",length=50)
	private String customerpo;

	public void setCustomerpo(String customerpo) {
		this.customerpo = customerpo;
	}

	public String getCustomerpo() {
		return customerpo;
	}

	@javax.persistence.Column(name="Discount",length=12)
	private double discount;

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public double getDiscount() {
		return discount;
	}

	@javax.persistence.Column(name="Freight",length=12)
	private double freight;

	public void setFreight(double freight) {
		this.freight = freight;
	}

	public double getFreight() {
		return freight;
	}

	@javax.persistence.Column(name="InvoiceNumber",length=20)
	private String invoicenumber;

	public void setInvoicenumber(String invoicenumber) {
		this.invoicenumber = invoicenumber;
	}

	public String getInvoicenumber() {
		return invoicenumber;
	}
	
	@javax.persistence.Column(name="BatchNumber",length=20)
	private String batchnumber;


	public String getBatchnumber() {
		if(StringUtils.isBlank(batchnumber)) {
			return StringUtils.EMPTY;
		}
		return batchnumber;
	}

	public void setBatchnumber(String batchnumber) {
		this.batchnumber = batchnumber;
	}

	@javax.persistence.Column(name="CustomerID",length=20)
	private String customerid;

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	public String getCustomerid() {
		return customerid;
	}

	@javax.persistence.Column(name="IsEmailed")
	private Boolean isemailed;

	public void setIsemailed(Boolean isemailed) {
		this.isemailed = isemailed;
	}

	public Boolean getIsemailed() {
		return isemailed;
	}

	@javax.persistence.Column(name="AmountPaid")
	private double amountpaid;

	public void setAmountpaid(double amountpaid) {
		this.amountpaid = amountpaid;
	}

	public double getAmountpaid() {
		return amountpaid;
	}

	@javax.persistence.Column(name="IsPrinted")
	private Boolean isprinted;

	public void setIsprinted(Boolean isprinted) {
		this.isprinted = isprinted;
	}

	public Boolean getIsprinted() {
		return isprinted;
	}

	@javax.persistence.Column(name="OrderAmount",length=12)
	private double orderamount;

	public void setOrderamount(double orderamount) {
		this.orderamount = orderamount;
	}

	public double getOrderamount() {
		return orderamount;
	}

	@javax.persistence.Column(name="OrderDate",length=19)
	@javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date orderdate;

	public void setOrderdate(java.util.Date orderdate) {
		this.orderdate = orderdate;
	}

	public java.util.Date getOrderdate() {
		return orderdate;
	}

	@javax.persistence.Column(name="OrderNumber",length=10)
	private String ordernumber;

	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	public String getOrdernumber() {
		return ordernumber;
	}

	@javax.persistence.Column(name="InvoiceDate",length=19)
	@javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date invoicedate;

	public void setInvoicedate(java.util.Date invoicedate) {
		this.invoicedate = invoicedate;
	}

	public java.util.Date getInvoicedate() {
		return invoicedate;
	}

	@javax.persistence.Column(name="ShipDate",length=19)
	@javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date shipdate;

	public void setShipdate(java.util.Date shipdate) {
		this.shipdate = shipdate;
	}

	public java.util.Date getShipdate() {
		return shipdate;
	}

	@javax.persistence.Column(name="Tax",length=12)
	private double tax;

	public void setTax(double tax) {
		this.tax = tax;
	}

	public double getTax() {
		return tax;
	}

	@javax.persistence.Column(name="TotalAmountShipped",length=22)
	private Double totalamountshipped;

	public void setTotalamountshipped(Double totalamountshipped) {
		this.totalamountshipped = totalamountshipped;
	}

	public Double getTotalamountshipped() {
		return totalamountshipped;
	}
	// <- Generated by DB Importer

	@Override
	public String toString() {
		return "Aropen [id=" + id + ", balance=" + balance + ", customerpo="
				+ customerpo + ", discount=" + discount + ", freight="
				+ freight + ", invoicenumber=" + invoicenumber
				+ ", batchnumber=" + batchnumber + ", customerid=" + customerid
				+ ", isemailed=" + isemailed + ", amountpaid=" + amountpaid
				+ ", isprinted=" + isprinted + ", orderamount=" + orderamount
				+ ", orderdate=" + orderdate + ", ordernumber=" + ordernumber
				+ ", invoicedate=" + invoicedate + ", shipdate=" + shipdate
				+ ", tax=" + tax + ", totalamountshipped=" + totalamountshipped
				+ "]";
	}
}