package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="barcodes")
public class Barcodes {
  @javax.persistence.Id
  //@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="barcode",length=50,nullable=false)
  private String barcode;

  public void setBarcode(String barcode) {
    this.barcode = barcode;
  }

  public String getBarcode() {
    return barcode;
  }

  @javax.persistence.Column(name="productid",length=50,nullable=false)
  private String productid = "";

  public void setProductid(String productid) {
    this.productid = productid;
  }

  public String getProductid() {
    return productid;
  }
// <- Generated by DB Importer
}