package com.oes.model.my_sql.entities;


// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="invoicelog")
public class Invoicelog {
	@javax.persistence.Id  
	@javax.persistence.Column(name="InvoiceNumber",length=20)
	private String invoicenumber;

	public void setInvoicenumber(String invoicenumber) {
		this.invoicenumber = invoicenumber;
	}

	public String getInvoicenumber() {
		return invoicenumber;
	}
	@javax.persistence.Column(name="BatchNumber",length=20)
	private String batchnumber;


	public String getBatchnumber() {
		return batchnumber;
	}

	public void setBatchnumber(String batchnumber) {
		this.batchnumber = batchnumber;
	}
	
	@javax.persistence.Column(name="CustomerID",length=20)
	private String customerid;

	public void setCustomerid(String customerid) {
		this.customerid = customerid;
	}

	public String getCustomerid() {
		return customerid;
	}

	@javax.persistence.Column(name="CustomerName",length=50)
	private String customername;

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	public String getCustomername() {
		return customername;
	}

	@javax.persistence.Column(name="CounterMan",length=50)
	private String counterman;

	public void setCounterman(String counterman) {
		this.counterman = counterman;
	}

	public String getCounterman() {
		return counterman;
	}


	@javax.persistence.Column(name="OrderAmount",length=12)
	private double orderamount;

	public void setOrderamount(double orderamount) {
		this.orderamount = orderamount;
	}

	public double getOrderamount() {
		return orderamount;
	}



	@javax.persistence.Column(name="OrderNumber",length=10)
	private String ordernumber;

	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	public String getOrdernumber() {
		return ordernumber;
	}

	@javax.persistence.Column(name="InvoiceDate",length=19)
	@javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	private java.util.Date invoicedate;

	public void setInvoicedate(java.util.Date invoicedate) {
		this.invoicedate = invoicedate;
	}

	public java.util.Date getInvoicedate() {
		return invoicedate;
	}


	@javax.persistence.Column(name="InvoiceAmount",length=22)
	private Double invoiceamount;

	public void setInvoiceamount(Double invoiceamount) {
		this.invoiceamount = invoiceamount;
	}

	public Double getInvoiceamount() {
		return invoiceamount;
	}
	// <- Generated by DB Importer

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((invoicenumber == null) ? 0 : invoicenumber.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Invoicelog other = (Invoicelog) obj;
		if (invoicenumber == null) {
			if (other.invoicenumber != null)
				return false;
		} else if (!invoicenumber.equals(other.invoicenumber))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Invoicelog [invoicenumber=");
		builder.append(invoicenumber);
		builder.append(", batchnumber=");
		builder.append(batchnumber);
		builder.append(", customerid=");
		builder.append(customerid);
		builder.append(", customername=");
		builder.append(customername);
		builder.append(", counterman=");
		builder.append(counterman);
		builder.append(", orderamount=");
		builder.append(orderamount);
		builder.append(", ordernumber=");
		builder.append(ordernumber);
		builder.append(", invoicedate=");
		builder.append(invoicedate);
		builder.append(", invoiceamount=");
		builder.append(invoiceamount);
		builder.append("]");
		return builder.toString();
	}

	
}