package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="itemhistory")
public class Itemhistory {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=19,nullable=false)
  private long id;

  public void setId(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  @javax.persistence.Column(name="customercode",length=10)
  private String customercode;

  public void setCustomercode(String customercode) {
    this.customercode = customercode;
  }

  public String getCustomercode() {
    return customercode;
  }

  @javax.persistence.Column(name="itemcode",length=100)
  private String itemcode;

  public void setItemcode(String itemcode) {
    this.itemcode = itemcode;
  }

  public String getItemcode() {
    return itemcode;
  }

  @javax.persistence.Column(name="itemdescription",length=50)
  private String itemdescription;

  public void setItemdescription(String itemdescription) {
    this.itemdescription = itemdescription;
  }

  public String getItemdescription() {
    return itemdescription;
  }

  @javax.persistence.Column(name="listprice",length=12)
  private Float listprice;

  public void setListprice(Float listprice) {
    this.listprice = listprice;
  }

  public Float getListprice() {
    return listprice;
  }

  @javax.persistence.Column(name="orderdate",length=10)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.DATE)
  private java.util.Date orderdate;

  public void setOrderdate(java.util.Date orderdate) {
    this.orderdate = orderdate;
  }

  public java.util.Date getOrderdate() {
    return orderdate;
  }

  @javax.persistence.Column(name="ordernumber",length=10,nullable=false)
  private String ordernumber = "";

  public void setOrdernumber(String ordernumber) {
    this.ordernumber = ordernumber;
  }

  public String getOrdernumber() {
    return ordernumber;
  }

  @javax.persistence.Column(name="priceentered",length=12)
  private Float priceentered;

  public void setPriceentered(Float priceentered) {
    this.priceentered = priceentered;
  }

  public Float getPriceentered() {
    return priceentered;
  }

  @javax.persistence.Column(name="quantityordered",length=10)
  private Integer quantityordered;

  public void setQuantityordered(Integer quantityordered) {
    this.quantityordered = quantityordered;
  }

  public Integer getQuantityordered() {
    return quantityordered;
  }

  @javax.persistence.Column(name="quantityshipped",length=10)
  private Integer quantityshipped;

  public void setQuantityshipped(Integer quantityshipped) {
    this.quantityshipped = quantityshipped;
  }

  public Integer getQuantityshipped() {
    return quantityshipped;
  }
  
  @javax.persistence.Column(name="quantityinvoice",length=10)
  private Integer quantityinvoice;

  public void setQuantityinvoice(Integer quantityinvoice) {
    this.quantityinvoice = quantityinvoice;
  }

  public Integer getQuantityinvoice() {
    return quantityinvoice;
  }
  
  @javax.persistence.Column(name="tax",length=12)
  private Float tax;

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public Float getTax() {
    return tax;
  }

}