package com.oes.model.my_sql.entities;

import com.mbi.oes.db.utils.StringPool;


// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="items")
public class Masteritem {
	@javax.persistence.Id
	//@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
	@javax.persistence.Column(name="ProductID",length=19,nullable=false)
	private String productid;

	public void setProductid(String productid) {
		this.productid = productid;
	}

	public String getProductid() {
		return productid;
	}
	@javax.persistence.Column(name="Category",length=50)
	private String category;

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCategory() {
		return category != null ? category : StringPool.BLANK;
	}


	@javax.persistence.Column(name="UoM",length=5)
	private String uom;

	public void setUom(String category) {
		this.uom = category;
	}

	public String getUom() {
		return uom != null ? uom : StringPool.BLANK;
	}
	
	@javax.persistence.Column(name="Description",length=50)
	private String description;

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		if(description == null) {
			return StringPool.BLANK;
		}
		return description;
	}

	@javax.persistence.Column(name="Description2",length=50)
	private String description2;

	public void setDescription2(String description2) {
		this.description2 = description2;
	}

	public String getDescription2() {
		return description2;
	}

	@javax.persistence.Column(name="DiscountA",length=12)
	private Float discounta;

	public void setDiscounta(Float discounta) {
		this.discounta = discounta;
	}

	public Float getDiscounta() {
		return discounta;
	}

	@javax.persistence.Column(name="DiscountB",length=12)
	private Float discountb;

	public void setDiscountb(Float discountb) {
		this.discountb = discountb;
	}

	public Float getDiscountb() {
		return discountb;
	}

	@javax.persistence.Column(name="DiscountC",length=12)
	private Float discountc;

	public void setDiscountc(Float discountc) {
		this.discountc = discountc;
	}

	public Float getDiscountc() {
		return discountc;
	}

	@javax.persistence.Column(name="DiscountD",length=12)
	private Float discountd;

	public void setDiscountd(Float discountd) {
		this.discountd = discountd;
	}

	public Float getDiscountd() {
		return discountd;
	}

	@javax.persistence.Column(name="DiscountE",length=12)
	private Float discounte;

	public void setDiscounte(Float discounte) {
		this.discounte = discounte;
	}

	public Float getDiscounte() {
		return discounte;
	}


	@javax.persistence.Column(name="ListPrice",length=12)
	private Float listprice;

	public void setListprice(Float listprice) {
		this.listprice = listprice;
	}

	public Float getListprice() {
		if(listprice == null) {
			return 0.0f;
		}
		return listprice;
	}



	@javax.persistence.Column(name="PriceA",length=12)
	private Float pricea;

	public void setPricea(Float pricea) {
		this.pricea = pricea;
	}

	public Float getPricea() {
		if(pricea == null) {
			return 0f;
		}
		return pricea;
	}

	@javax.persistence.Column(name="PriceB",length=12)
	private Float priceb;

	public void setPriceb(Float priceb) {
		this.priceb = priceb;
	}

	public Float getPriceb() {
		if(priceb == null) {
			return 0f;
		}
		return priceb;
	}

	@javax.persistence.Column(name="PriceC",length=12)
	private Float pricec;

	public void setPricec(Float pricec) {
		this.pricec = pricec;
	}

	public Float getPricec() {
		if(pricec == null) {
			return 0f;
		}
		return pricec;
	}

	@javax.persistence.Column(name="PriceCode",length=50)
	private String pricecode;

	public void setPricecode(String pricecode) {
		this.pricecode = pricecode;
	}

	public String getPricecode() {
		return pricecode;
	}

	@javax.persistence.Column(name="PriceD",length=12)
	private Float priced;

	public void setPriced(Float priced) {
		this.priced = priced;
	}

	public Float getPriced() {
		if(priced == null) {
			return 0f;
		}
		return priced;
	}

	@javax.persistence.Column(name="PriceE",length=12)
	private Float pricee;

	public void setPricee(Float pricee) {
		this.pricee = pricee;
	}

	public Float getPricee() {
		if(pricee == null) {
			return 0f;
		}
		return pricee;
	}

	@javax.persistence.Column(name="ProductCategory",length=50)
	private String productcategory;

	public void setProductcategory(String productcategory) {
		this.productcategory = productcategory;
	}

	public String getProductcategory() {
		return productcategory == null ? StringPool.BLANK : productcategory;
	}


	@javax.persistence.Column(name="SubCategoryID",length=50)
	private String subcategoryid;

	public void setSubcategoryid(String subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	public String getSubcategoryid() {
		return subcategoryid != null ? subcategoryid : StringPool.BLANK;
	}

	@javax.persistence.Column(name="TaxCode",length=5)
	private String taxcode;

	public void setTaxcode(String taxcode) {
		this.taxcode = taxcode;
	}

	public String getTaxcode() {
		return taxcode;
	}

	@javax.persistence.Column(name="UPCCode",length=50)
	private String upccode;

	public void setUpccode(String upccode) {
		this.upccode = upccode;
	}

	public String getUpccode() {
		return upccode;
	}

	@javax.persistence.Column(name="VendorID",length=19)
	private String vendorid;

	public void setVendorid(String vendorid) {
		this.vendorid = vendorid;
	}

	public String getVendorid() {
		return vendorid;
	}

	@javax.persistence.Column(name="WebDescription",length=50)
	private String webdescription;

	public void setWebdescription(String webdescription) {
		this.webdescription = webdescription;
	}

	public String getWebdescription() {
		return webdescription;
	}

	@javax.persistence.Column(name="WebGraphicsFile",length=2147483647)
	private byte[] webgraphicsfile;

	public void setWebgraphicsfile(byte[] webgraphicsfile) {
		this.webgraphicsfile = webgraphicsfile;
	}

	public byte[] getWebgraphicsfile() {
		return webgraphicsfile;
	}
	
	@javax.persistence.Column(name="importqty",length=10)
	private int importqty;

	public void setimportqty(int importqty) {
		this.importqty = importqty;
	}

	public int getimportqty() {
		return importqty;
	}
	
}