package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="orderdetails")
public class Orderdetails {
	
	@javax.persistence.Id
	  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.IDENTITY)
	  private long id;
	public long getId(){
		return id;
	}
	public void setId(long id){
		this.id = id;
	}
	
	
  //@javax.persistence.Id
  //@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="OrderNumber",length=10,nullable=false)
  private String ordernumber;

  public void setOrdernumber(String ordernumber) {
    this.ordernumber = ordernumber;
  }

  public String getOrdernumber() {
    return ordernumber;
  }

  @javax.persistence.Column(name="Commission",length=12)
  private Float commission;

  public void setCommission(Float commission) {
    this.commission = commission;
  }

  public Float getCommission() {
    return commission;
  }

  @javax.persistence.Column(name = "OrderDate", length = 20)
	@javax.persistence.Temporal(value = javax.persistence.TemporalType.DATE)
	private java.util.Date orderdate;

	public void setOrderdate(java.util.Date orderdate) {
		this.orderdate = orderdate;
	}

	public java.util.Date getOrderdate() {
		return orderdate;
	}
	
  @javax.persistence.Column(name="ItemStatus",length=10)
  private String itemstatus;

  public void setItemstatus(String itemstatus) {
    this.itemstatus = itemstatus;
  }
  
  public String getItemstatus() {
	  return itemstatus;
  }
  
  @javax.persistence.Column(name="CustomerCode",length=10)
  private String customercode;

  public void setCustomercode(String customercode) {
    this.customercode = customercode;
  }

  public String getCustomercode() {
    return customercode;
  }

  @javax.persistence.Column(name="InvoiceNumber",length=10)
  private String invoicenumber;

  public void setInvoicenumber(String invoicenumber) {
    this.invoicenumber = invoicenumber;
  }

  public String getInvoicenumber() {
    return invoicenumber;
  }

  @javax.persistence.Column(name="ItemCode",length=30)
  private String itemcode;

  public void setItemcode(String itemcode) {
    this.itemcode = itemcode;
  }

  public String getItemcode() {
    return itemcode;
  }

  @javax.persistence.Column(name="ItemDescription",length=150)
  private String itemdescription;

  public void setItemdescription(String itemdescription) {
    this.itemdescription = itemdescription;
  }

  public String getItemdescription() {
    return itemdescription;
  }

  @javax.persistence.Column(name="ItemDiscount",length=12)
  private Float itemdiscount;

  public void setItemdiscount(Float itemdiscount) {
    this.itemdiscount = itemdiscount;
  }

  public Float getItemdiscount() {
    return itemdiscount;
  }

  @javax.persistence.Column(name="ListPrice",length=12)
  private Float listprice;

  public void setListprice(Float listprice) {
    this.listprice = listprice;
  }

  public Float getListprice() {
    return listprice;
  }

  @javax.persistence.Column(name="OrderDiscount",length=12)
  private Float orderdiscount;

  public void setOrderdiscount(Float orderdiscount) {
    this.orderdiscount = orderdiscount;
  }

  public Float getOrderdiscount() {
    return orderdiscount;
  }

  @javax.persistence.Column(name="Note",length=100)
  private String note;

  public void setNote(String note) {
    this.note = note;
  }

  public String getNote() {
    return note;
  }
  
  @javax.persistence.Column(name="PriceAdjustment",length=12)
  private Float priceadjustment;

  public void setPriceadjustment(Float priceadjustment) {
    this.priceadjustment = priceadjustment;
  }

  public Float getPriceadjustment() {
    return priceadjustment;
  }

  @javax.persistence.Column(name="PriceEntered",length=12)
  private Float priceentered;

  public void setPriceentered(Float priceentered) {
    this.priceentered = priceentered;
  }

  public Float getPriceentered() {
    return priceentered;
  }

  @javax.persistence.Column(name="QuantityBackOrdered",length=10)
  private Integer quantitybackordered;

  public void setQuantitybackordered(Integer quantitybackordered) {
    this.quantitybackordered = quantitybackordered;
  }

  public Integer getQuantitybackordered() {
    return quantitybackordered;
  }

  @javax.persistence.Column(name="QuantityInvoice",length=10)
  private Integer quantityinvoice;

  public void setQuantityinvoice(Integer quantityinvoice) {
    this.quantityinvoice = quantityinvoice;
  }

  public Integer getQuantityinvoice() {
    return quantityinvoice;
  }

  @javax.persistence.Column(name="QuantityOrdered",length=10)
  private Integer quantityordered;

  public void setQuantityordered(Integer quantityordered) {
    this.quantityordered = quantityordered;
  }

  public Integer getQuantityordered() {
	  if(quantityordered == null) {
		  return 0;
	  }
	  return quantityordered;
  }

  @javax.persistence.Column(name="QuantityShipped",length=10)
  private Integer quantityshipped;

  public void setQuantityshipped(Integer quantityshipped) {
    this.quantityshipped = quantityshipped;
  }

  public Integer getQuantityshipped() {
	  if(quantityshipped == null) {
		  return 0;
	  }
    return quantityshipped;
  }

  @javax.persistence.Column(name="StandardPrice",length=12)
  private Float standardprice;

  public void setStandardprice(Float standardprice) {
    this.standardprice = standardprice;
  }

  public Float getStandardprice() {
    return standardprice;
  }

  @javax.persistence.Column(name="Tax",length=12)
  private Float tax;

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public Float getTax() {
    return tax;
  }

  @javax.persistence.Column(name="UOM",length=45)
  private String uom;

  public void setUom(String uom) {
    this.uom = uom;
  }

  public String getUom() {
    return uom;
  }
// <- Generated by DB Importer
@Override
public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("Orderdetails [id=");
	builder.append(id);
	builder.append(", ordernumber=");
	builder.append(ordernumber);
	builder.append(", commission=");
	builder.append(commission);
	builder.append(", customercode=");
	builder.append(customercode);
	builder.append(", invoicenumber=");
	builder.append(invoicenumber);
	builder.append(", itemcode=");
	builder.append(itemcode);
	builder.append(", itemdescription=");
	builder.append(itemdescription);
	builder.append(", itemdiscount=");
	builder.append(itemdiscount);
	builder.append(", listprice=");
	builder.append(listprice);
	builder.append(", orderdiscount=");
	builder.append(orderdiscount);
	builder.append(", priceadjustment=");
	builder.append(priceadjustment);
	builder.append(", priceentered=");
	builder.append(priceentered);
	builder.append(", quantitybackordered=");
	builder.append(quantitybackordered);
	builder.append(", quantityinvoice=");
	builder.append(quantityinvoice);
	builder.append(", quantityordered=");
	builder.append(quantityordered);
	builder.append(", quantityshipped=");
	builder.append(quantityshipped);
	builder.append(", standardprice=");
	builder.append(standardprice);
	builder.append(", tax=");
	builder.append(tax);
	builder.append(", uom=");
	builder.append(uom);
	builder.append("]");
	return builder.toString();
}
}