package com.oes.model.my_sql.entities;

import com.mbi.oes.db.utils.StringPool;


// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name = "orders")
public class Orders {
	@javax.persistence.Id
	// @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
	@javax.persistence.Column(name = "OrderNumber", length = 10, nullable = false)
	private String ordernumber;

	public void setOrdernumber(String ordernumber) {
		this.ordernumber = ordernumber;
	}

	public String getOrdernumber() {
		return ordernumber;
	}

	@javax.persistence.Column(name = "CancelBackOrder", length = 10)
	private String cancelbackorder;

	public void setCancelbackorder(String cancelbackorder) {
		this.cancelbackorder = cancelbackorder;
	}

	public String getCancelbackorder() {
		return cancelbackorder;
	}

	@javax.persistence.Column(name = "CashDeposit4CCOrdr", length = 10)
	private String cashdeposit4ccordr;

	public void setCashdeposit4ccordr(String cashdeposit4ccordr) {
		this.cashdeposit4ccordr = cashdeposit4ccordr;
	}

	public String getCashdeposit4ccordr() {
		return cashdeposit4ccordr;
	}

	@javax.persistence.Column(name = "CheckedNPickedBy", length = 45)
	private String checkednpickedby;

	public void setCheckednpickedby(String checkednpickedby) {
		this.checkednpickedby = checkednpickedby;
	}

	public String getCheckednpickedby() {
		return checkednpickedby;
	}

	@javax.persistence.Column(name = "CommissionPercent", length = 12)
	private Float commissionpercent;

	public void setCommissionpercent(Float commissionpercent) {
		this.commissionpercent = commissionpercent;
	}

	public Float getCommissionpercent() {
		return commissionpercent;
	}

	@javax.persistence.Column(name = "CounterMan", length = 10)
	private String counterman;

	public void setCounterman(String counterman) {
		this.counterman = counterman;
	}

	public String getCounterman() {
		return counterman;
	}

	@javax.persistence.Column(name = "CountyCode", length = 10)
	private String countycode;

	public void setCountycode(String countycode) {
		this.countycode = countycode;
	}

	public String getCountycode() {
		return countycode;
	}

	@javax.persistence.Column(name = "CreditType", length = 15)
	private String credittype;

	public void setCredittype(String credittype) {
		this.credittype = credittype;
	}

	public String getCredittype() {
		return credittype;
	}

	@javax.persistence.Column(name = "CustomerCode", length = 10)
	private String customercode;

	public void setCustomercode(String customercode) {
		this.customercode = customercode;
	}

	public String getCustomercode() {
		return customercode;
	}

	@javax.persistence.Column(name = "CustomerPO", length = 20)
	private String customerpo;

	public void setCustomerpo(String customerpo) {
		this.customerpo = customerpo;
	}

	public String getCustomerpo() {
		return customerpo != null ? customerpo : "";
	}

	@javax.persistence.Column(name = "Freight", length = 10)
	private float freight;

	public void setFreight(float freight) {
		this.freight = freight;
	}

	public float getFreight() {
		return freight;
	}

	@javax.persistence.Column(name = "FreightCode", length = 10)
	private String freightcode;

	public void setFreightcode(String freightcode) {
		this.freightcode = freightcode;
	}

	public String getFreightcode() {
		return freightcode;
	}

	@javax.persistence.Column(name = "InvoiceDate", length = 10)
	@javax.persistence.Temporal(value = javax.persistence.TemporalType.DATE)
	private java.util.Date invoicedate;

	public void setInvoicedate(java.util.Date invoicedate) {
		this.invoicedate = invoicedate;
	}

	public java.util.Date getInvoicedate() {
		return invoicedate;
	}

	@javax.persistence.Column(name = "Misc", length = 5)
	private String misc;

	public void setMisc(String misc) {
		this.misc = misc;
	}

	public String getMisc() {
		return misc;
	}

	@javax.persistence.Column(name = "NetAmount", length = 12)
	private Float netamount;

	public void setNetamount(Float netamount) {
		this.netamount = netamount;
	}

	public Float getNetamount() {
		return netamount;
	}

	@javax.persistence.Column(name = "Notes", length = 45)
	private String notes;

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public String getNotes() {
		return notes;
	}

	@javax.persistence.Column(name = "OrderDate", length = 10)
	@javax.persistence.Temporal(value = javax.persistence.TemporalType.DATE)
	private java.util.Date orderdate;

	public void setOrderdate(java.util.Date orderdate) {
		this.orderdate = orderdate;
	}

	public java.util.Date getOrderdate() {
		return orderdate;
	}

	@javax.persistence.Column(name = "OrderStatus", length = 5)
	private String orderstatus;

	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

	public String getOrderstatus() {
		return orderstatus;
	}

	@javax.persistence.Column(name = "POSPaid", length = 10)
	private String pospaid;

	public void setPospaid(String pospaid) {
		this.pospaid = pospaid;
	}

	public String getPospaid() {
		return pospaid;
	}

	@javax.persistence.Column(name = "PickingListPrntd", length = 4)
	private String pickinglistprntd;

	public void setPickinglistprntd(String pickinglistprntd) {
		this.pickinglistprntd = pickinglistprntd;
	}

	public String getPickinglistprntd() {
		return pickinglistprntd;
	}

	@javax.persistence.Column(name = "PrintOnce", length = 5)
	private String printonce;

	public void setPrintonce(String printonce) {
		this.printonce = printonce;
	}

	public String getPrintonce() {
		return printonce;
	}

	@javax.persistence.Column(name = "ResaleNo", length = 15)
	private String resaleno;

	public void setResaleno(String resaleno) {
		this.resaleno = resaleno;
	}

	public String getResaleno() {
		return resaleno;
	}

	@javax.persistence.Column(name = "SalesMan", length = 15)
	private String salesman;

	public void setSalesman(String salesman) {
		this.salesman = salesman;
	}

	public String getSalesman() {
		return salesman;
	}

	@javax.persistence.Column(name = "SequenceNum", length = 10)
	private String sequencenum;

	public void setSequencenum(String sequencenum) {
		this.sequencenum = sequencenum;
	}

	public String getSequencenum() {
		return sequencenum;
	}

	@javax.persistence.Column(name = "ShipAddr1", length = 45)
	private String shipaddr1;

	public void setShipaddr1(String shipaddr1) {
		this.shipaddr1 = shipaddr1;
	}

	public String getShipaddr1() {
		return shipaddr1;
	}

	@javax.persistence.Column(name = "ShipAddr2", length = 45)
	private String shipaddr2;

	public void setShipaddr2(String shipaddr2) {
		this.shipaddr2 = shipaddr2;
	}

	public String getShipaddr2() {
		return shipaddr2;
	}

	@javax.persistence.Column(name = "ShipAddr3", length = 45)
	private String shipaddr3;

	public void setShipaddr3(String shipaddr3) {
		this.shipaddr3 = shipaddr3;
	}

	public String getShipaddr3() {
		return shipaddr3;
	}

	@javax.persistence.Column(name = "ShipDate", length = 10)
	@javax.persistence.Temporal(value = javax.persistence.TemporalType.DATE)
	private java.util.Date shipdate;

	public void setShipdate(java.util.Date shipdate) {
		this.shipdate = shipdate;
	}

	public java.util.Date getShipdate() {
		return shipdate;
	}

	@javax.persistence.Column(name = "ShipFrom", length = 25)
	private String shipfrom;

	public void setShipfrom(String shipfrom) {
		this.shipfrom = shipfrom;
	}

	public String getShipfrom() {
		return shipfrom;
	}

	@javax.persistence.Column(name = "ShipMethod", length = 15)
	private String shipmethod;

	public void setShipmethod(String shipmethod) {
		this.shipmethod = shipmethod;
	}

	public String getShipmethod() {
		return shipmethod;
	}

	@javax.persistence.Column(name = "ShipName", length = 30)
	private String shipname;

	public void setShipname(String shipname) {
		this.shipname = shipname;
	}

	public String getShipname() {
		return shipname;
	}

	@javax.persistence.Column(name = "ShipVia", length = 45)
	private String shipvia;

	public void setShipvia(String shipvia) {
		this.shipvia = shipvia;
	}

	public String getShipvia() {
		return shipvia;
	}

	@javax.persistence.Column(name = "ShipZip", length = 10)
	private String shipzip;

	public void setShipzip(String shipzip) {
		this.shipzip = shipzip;
	}

	public String getShipzip() {
		return shipzip;
	}

	@javax.persistence.Column(name = "SoldAddr1", length = 45)
	private String soldaddr1;

	public void setSoldaddr1(String soldaddr1) {
		this.soldaddr1 = soldaddr1;
	}

	public String getSoldaddr1() {
		return soldaddr1;
	}

	@javax.persistence.Column(name = "SoldAddr2", length = 45)
	private String soldaddr2;

	public void setSoldaddr2(String soldaddr2) {
		this.soldaddr2 = soldaddr2;
	}

	public String getSoldaddr2() {
		return soldaddr2;
	}

	@javax.persistence.Column(name = "SoldAddr3", length = 45)
	private String soldaddr3;

	public void setSoldaddr3(String soldaddr3) {
		this.soldaddr3 = soldaddr3;
	}

	public String getSoldaddr3() {
		return soldaddr3;
	}

	@javax.persistence.Column(name = "SoldName", length = 30)
	private String soldname;

	public void setSoldname(String soldname) {
		this.soldname = soldname;
	}

	public String getSoldname() {
		return soldname;
	}

	@javax.persistence.Column(name = "Tax", length = 12)
	private Float tax;

	public void setTax(Float tax) {
		this.tax = tax;
	}

	public Float getTax() {
		return tax;
	}

	@javax.persistence.Column(name = "TaxPercent", length = 5)
	private String taxpercent;

	public void setTaxpercent(String taxpercent) {
		this.taxpercent = taxpercent;
	}

	public String getTaxpercent() {
		return taxpercent;
	}

	@javax.persistence.Column(name = "TermNum", length = 15)
	private String termnum;

	public void setTermnum(String termnum) {
		this.termnum = termnum;
	}

	public String getTermnum() {
		return termnum;
	}

	@javax.persistence.Column(name = "Terms", length = 45)
	private String terms;

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public String getTerms() {
		return terms;
	}

	@javax.persistence.Column(name = "Weights", length = 10)
	private String weights;

	public void setWeights(String weights) {
		this.weights = weights;
	}

	public String getWeights() {
		return weights;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((ordernumber == null) ? 0 : ordernumber.hashCode());
		return result;
	}
	
	  @javax.persistence.Column(name="printtime",length=19)
	  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	  private java.util.Date printtime;

	  public void setPrinttime(java.util.Date printtime) {
	    this.printtime = printtime;
	  }

	  public java.util.Date getPrinttime() {
	    return printtime;
	  }
	  
	  @javax.persistence.Column(name="packtime",length=19)
	  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	  private java.util.Date packtime;

	  public void setPacktime(java.util.Date printtime) {
	    this.packtime = printtime;
	  }

	  public java.util.Date getPacktime() {
	    return packtime;
	  }
	  
	  @javax.persistence.Column(name="trucktime",length=19)
	  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	  private java.util.Date trucktime;

	  public void setTrucktime(java.util.Date trucktime) {
	    this.trucktime = trucktime;
	  }

	  public java.util.Date getTrucktime() {
	    return trucktime;
	  }
	  
	  @javax.persistence.Column(name="shiptime",length=19)
	  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
	  private java.util.Date shiptime;

	  public void setShiptime(java.util.Date shiptime) {
	    this.shiptime = shiptime;
	  }

	  public java.util.Date getShiptime() {
	    return shiptime;
	  }
	  
	  @javax.persistence.Column(name="DeliveryType",length=20)
	  private String deliverytype;
	  public void setDeliverytype(String deliverytype) {
			this.deliverytype = deliverytype;
	  }

	  public String getDeliverytype() {
		  if(deliverytype == null) {
			  return StringPool.BLANK;
		  }
		  return deliverytype;
	  }

	  @javax.persistence.Column(name="Status",length=20)
	  private String status;

	  public void setStatus(String status) {
	    this.status = status;
	  }

	  public String getStatus() {
		  if(status == null) {
			  status = StringPool.BLANK;
		  }
	    return status;
	  }
	  
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Orders other = (Orders) obj;
		if (ordernumber == null) {
			if (other.ordernumber != null)
				return false;
		} else if (!ordernumber.equals(other.ordernumber))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Orders [ordernumber=" + ordernumber + ", cancelbackorder="
				+ cancelbackorder + ", cashdeposit4ccordr="
				+ cashdeposit4ccordr + ", checkednpickedby=" + checkednpickedby
				+ ", commissionpercent=" + commissionpercent + ", counterman="
				+ counterman + ", countycode=" + countycode + ", credittype="
				+ credittype + ", customercode=" + customercode
				+ ", customerpo=" + customerpo + ", freight=" + freight
				+ ", freightcode=" + freightcode + ", invoicedate=" + invoicedate
				+ ", misc=" + misc + ", netamount=" + netamount + ", notes="
				+ notes + ", orderdate=" + orderdate + ", orderstatus="
				+ orderstatus + ", pospaid=" + pospaid + ", pickinglistprntd="
				+ pickinglistprntd + ", printonce=" + printonce + ", resaleno="
				+ resaleno + ", salesman=" + salesman + ", sequencenum="
				+ sequencenum + ", shipaddr1=" + shipaddr1 + ", shipaddr2="
				+ shipaddr2 + ", shipaddr3=" + shipaddr3 + ", shipdate="
				+ shipdate + ", shipfrom=" + shipfrom + ", shipmethod="
				+ shipmethod + ", shipname=" + shipname + ", shipvia="
				+ shipvia + ", shipzip=" + shipzip + ", soldaddr1=" + soldaddr1
				+ ", soldaddr2=" + soldaddr2 + ", soldaddr3=" + soldaddr3
				+ ", soldname=" + soldname + ", tax=" + tax + ", taxpercent="
				+ taxpercent + ", termnum=" + termnum + ", terms=" + terms
				+ ", weights=" + weights + "]";
	}

	// <- Generated by DB Importer
}