package com.oes.model.my_sql.entities;

import com.mbi.oes.db.utils.StringPool;


// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="orderslog")
public class Orderslog {
  @javax.persistence.Id
  //@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="OrderNumber",length=10,nullable=false)
  private String ordernumber;

  public void setOrdernumber(String ordernumber) {
    this.ordernumber = ordernumber;
  }

  public String getOrdernumber() {
    return ordernumber;
  }

  @javax.persistence.Column(name="CounterMan",length=10)
  private String counterman;

  public void setCounterman(String counterman) {
    this.counterman = counterman;
  }

  public String getCounterman() {
	  if(counterman == null) {
		  counterman = StringPool.BLANK;
	  }
    return counterman;
  }

  @javax.persistence.Column(name="Status",length=20)
  private String status;

  public void setStatus(String status) {
    this.status = status;
  }

  public String getStatus() {
	  if(status == null) {
		  status = StringPool.BLANK;
	  }
    return status;
  }
  
  @javax.persistence.Column(name="Customercode",length=10)
  private String customercode;

  public void setCustomercode(String customercode) {
    this.customercode = customercode;
  }

  public String getCustomercode() {
    return customercode;
  }

  @javax.persistence.Column(name="NetAmount",length=12)
  private Float netamount;

  public void setNetamount(Float netamount) {
    this.netamount = netamount;
  }

  public Float getNetamount() {
    return netamount;
  }

  @javax.persistence.Column(name="OrderCreationDate",length=10)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.DATE)
  private java.util.Date ordercreationdate;

  public void setOrdercreationdate(java.util.Date ordercreationdate) {
    this.ordercreationdate = ordercreationdate;
  }

  public java.util.Date getOrdercreationdate() {
    return ordercreationdate;
  }
  
  @javax.persistence.Column(name="OrderDate",length=10)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.DATE)
  private java.util.Date orderdate;

  public void setOrderdate(java.util.Date orderdate) {
    this.orderdate = orderdate;
  }

  public java.util.Date getOrderdate() {
    return orderdate;
  }

  @javax.persistence.Column(name="Tax",length=12)
  private Float tax;

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public Float getTax() {
    return tax;
  }

  @javax.persistence.Column(name="ShippingAddress",length=50)
  private String shippingaddress;
  public void setShippingAddress(String shippingaddress) {
		this.shippingaddress = shippingaddress;
  }

  public String getShippingaddress() {
	  if(shippingaddress == null) {
		  return StringPool.BLANK;
	  }
	  return shippingaddress;
  }
  
  @javax.persistence.Column(name="ShipZip",length=10)
  private String shipzip;
  public void setShipZip(String shipzip) {
	this.shipzip = shipzip;
  }
  
  public String getShipzip() {
	  if(shipzip == null) {
		  return StringPool.BLANK;
	  }
	  return shipzip;
  }
  
  @javax.persistence.Column(name="printtime",length=19)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
  private java.util.Date printtime;

  public void setPrinttime(java.util.Date printtime) {
    this.printtime = printtime;
  }

  public java.util.Date getPrinttime() {
    return printtime;
  }
  
  @javax.persistence.Column(name="packtime",length=19)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
  private java.util.Date packtime;

  public void setPacktime(java.util.Date printtime) {
    this.packtime = printtime;
  }

  public java.util.Date getPacktime() {
    return packtime;
  }
  
  @javax.persistence.Column(name="trucktime",length=19)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
  private java.util.Date trucktime;

  public void setTrucktime(java.util.Date trucktime) {
    this.trucktime = trucktime;
  }

  public java.util.Date getTrucktime() {
    return trucktime;
  }
  
  @javax.persistence.Column(name="shiptime",length=19)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.TIMESTAMP)
  private java.util.Date shiptime;

  public void setShiptime(java.util.Date shiptime) {
    this.shiptime = shiptime;
  }

  public java.util.Date getShiptime() {
    return shiptime;
  }
  
  @javax.persistence.Column(name="Packer",length=30)
  private String packer;
  public void setPacker(String packer) {
		this.packer = packer;
  }

  public String getPacker() {
	  if(packer == null) {
		  return StringPool.BLANK;
	  }
	  return packer;
  }
  
  @javax.persistence.Column(name="Driver",length=30)
  private String driver;
  public void setDriver(String driver) {
		this.driver = driver;
  }

  public String getDriver() {
	  if(driver == null) {
		  return StringPool.BLANK;
	  }
	  return driver;
  }
  
  @javax.persistence.Column(name="DeliveryType",length=20)
  private String deliverytype;
  public void setDeliverytype(String deliverytype) {
		this.deliverytype = deliverytype;
  }

  public String getDeliverytype() {
	  if(deliverytype == null) {
		  return StringPool.BLANK;
	  }
	  return deliverytype;
  }

  
  @javax.persistence.Column(name = "ShipDate", length = 10)
	@javax.persistence.Temporal(value = javax.persistence.TemporalType.DATE)
	private java.util.Date shipdate;

	public void setShipdate(java.util.Date shipdate) {
		this.shipdate = shipdate;
	}

	public java.util.Date getShipdate() {
		return shipdate;
	}
  
}

