package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="podetails")
public class Podetails {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=10,nullable=false)
  private int id;

  public void setId(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  @javax.persistence.Column(name="itemdescription",length=45)
  private String itemdescription;

  public void setItemdescription(String itemdescription) {
    this.itemdescription = itemdescription;
  }

  public String getItemdescription() {
    return itemdescription;
  }

  @javax.persistence.Column(name="itemcode",length=45)
  private String itemcode;

  public void setItemcode(String itemcode) {
    this.itemcode = itemcode;
  }

  public String getItemcode() {
    return itemcode;
  }

  @javax.persistence.Column(name="itemstatus",length=45)
  private String itemstatus;

  public void setItemstatus(String itemstatus) {
    this.itemstatus = itemstatus;
  }

  public String getItemstatus() {
    return itemstatus;
  }

  @javax.persistence.Column(name="listprice",length=12)
  private Float listprice;

  public void setListprice(Float listprice) {
    this.listprice = listprice;
  }

  public Float getListprice() {
    return listprice;
  }

  @javax.persistence.Column(name="ponumber",length=45)
  private String ponumber;

  public void setPonumber(String ponumber) {
    this.ponumber = ponumber;
  }

  public String getPonumber() {
    return ponumber;
  }

  @javax.persistence.Column(name="quantityordered",length=10)
  private Integer quantityordered;

  public void setQuantityordered(Integer quantityordered) {
    this.quantityordered = quantityordered;
  }

  public Integer getQuantityordered() {
    return quantityordered;
  }

  @javax.persistence.Column(name="quantityreceived",length=10)
  private Integer quantityreceived;

  public void setQuantityreceived(Integer quantityreceived) {
    this.quantityreceived = quantityreceived;
  }

  public Integer getQuantityreceived() {
    return quantityreceived;
  }

  @javax.persistence.Column(name="tax",length=12)
  private Float tax;

  public void setTax(Float tax) {
    this.tax = tax;
  }

  public Float getTax() {
    return tax;
  }

  @javax.persistence.Column(name="uom",length=45)
  private String uom;

  public void setUom(String uom) {
    this.uom = uom;
  }

  public String getUom() {
    return uom;
  }
// <- Generated by DB Importer
}