package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="productcategories", uniqueConstraints={@javax.persistence.UniqueConstraint(columnNames={"category"})})
public class Productcategories {
  @javax.persistence.Id
  //@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=10,nullable=false)
  private int id;

  public void setId(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  @javax.persistence.Column(name="category",length=45,nullable=false)
  private String category = "";

  public void setCategory(String category) {
    this.category = category;
  }

  public String getCategory() {
    return category;
  }
  
  @javax.persistence.Column(name="productcategory",length=45,nullable=false)
  private String productcategory = "";

  public void setProductCategory(String productcategory) {
    this.productcategory = productcategory;
  }

  public String getProductCategory() {
    return productcategory;
  }
// <- Generated by DB Importer

@Override
public String toString() {
	StringBuilder builder = new StringBuilder();
	builder.append("Productcategories [id=");
	builder.append(id);
	builder.append(", category=");
	builder.append(category);
	builder.append("]");
	return builder.toString();
}
}