package com.oes.model.my_sql.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.ElementCollection;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

import org.hibernate.annotations.CollectionOfElements;
import org.hibernate.annotations.IndexColumn;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="Reports")
public class Reports {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=19,nullable=false)
  private long id;

  public void setId(long id) {
    this.id = id;
  }

  public long getId() {
    return id;
  }

  @javax.persistence.Column(name="reportname",length=50)
  private String reportname;

  public void setReportname(String reportname) {
    this.reportname = reportname;
  }

  public String getReportname() {
    return reportname;
  }
  
  @javax.persistence.Column(name="basetable",length=20)
  private String basetable;

  public void setBasetable(String basetable) {
    this.basetable = basetable;
  }

  public String getBasetable() {
    return basetable;
  }
  
  @javax.persistence.Column(name="createdby",length=20)
  private String createdby;

  public void setCreatedby(String createdby) {
    this.createdby = createdby;
  }

  public String getCreatedby() {
    return createdby;
  }

  @CollectionOfElements
  @CollectionTable(name="inputfields")
  private List<String> inputfields = new ArrayList<String>();
  public void setInputfields(List<String> inputfields) {
	  this.inputfields = inputfields;
  }
  
  public List<String> getInputfields(){
	  return inputfields;
  }
  
 // @ElementCollection //@IndexColumn(name="outputfield_index")
  @CollectionOfElements
  @CollectionTable(name="outputfields")
  private List<String> outputfields = new ArrayList<String>();
  public void setOutputfields(List<String> outputfields) {
	  this.outputfields = outputfields;
  }
  
  public List<String> getOutputfields(){
	  return outputfields;
  }
  
  @CollectionOfElements
  @CollectionTable(name="summaryfields")
  private List<String> summaryfields = new ArrayList<String>();
  public void setSummaryfields(List<String> summaryfields) {
	  this.summaryfields = summaryfields;
  }
  
  public List<String> getSummaryfields(){
	  return summaryfields;
  }
  
  @javax.persistence.Column(name="createddate",length=20)
  @javax.persistence.Temporal(value=javax.persistence.TemporalType.DATE)
  private java.util.Date createddate;

  public void setCreateddate(java.util.Date createddate) {
    this.createddate = createddate;
  }

  public java.util.Date getCreateddate() {
    return createddate;
  }

}