package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="user", uniqueConstraints={@javax.persistence.UniqueConstraint(columnNames={"LoginPassword"})})
public class User {
	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
	@javax.persistence.Column(name="id",length=19,nullable=false)
	private long id;

	public void setId(long id) {
		this.id = id;
	}

	public long getId() {
		return id;
	}

	@javax.persistence.Column(name="Address",length=100)
	private String address;

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

	@javax.persistence.Column(name="DOB",length=10)
	@javax.persistence.Temporal(value=javax.persistence.TemporalType.DATE)
	private java.util.Date dob;

	public void setDob(java.util.Date dob) {
		this.dob = dob;
	}

	public java.util.Date getDob() {
		return dob;
	}

	@javax.persistence.Column(name="Designation",length=50)
	private String designation;

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDesignation() {
		return designation;
	}

	@javax.persistence.Column(name="WareHouseID",length=2)

	private int warehouseid;

	public void setWarehouseid(int warehouseid) {
		this.warehouseid = warehouseid;
	}

	public int getWarehouseid() {
		return warehouseid;
	}

	@javax.persistence.Column(name="EmpCode",length=20,nullable=false)
	private String empcode = "";

	public void setEmpcode(String empcode) {
		this.empcode = empcode;
	}

	public String getEmpcode() {
		return empcode;
	}

	@javax.persistence.Column(name="EmpName",length=20,nullable=false)
	private String empname = "";

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public String getEmpname() {
		return empname;
	}

	@javax.persistence.Column(name="LoginName",length=50,nullable=false)
	private String loginname = "";

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginname() {
		return loginname;
	}

	@javax.persistence.Column(name="LoginPassword",length=50,nullable=false)
	private String loginpassword = "";

	public void setLoginpassword(String loginpassword) {
		this.loginpassword = loginpassword;
	}

	public String getLoginpassword() {
		return loginpassword;
	}

	@javax.persistence.Column(name="Phone",length=15)
	private String phone;

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhone() {
		return phone;
	}

	@javax.persistence.Column(name="Port",length=10)
	private String port = "";

	public void setPort(String port) {
		this.port = port;
	}

	public String getPort() {
		return port;
	}

	@javax.persistence.Column(name="SMTPPassword",length=50)
	private String smtppassword = "";

	public void setSmtppassword(String smtppassword) {
		this.smtppassword = smtppassword;
	}

	public String getSmtppassword() {
		return smtppassword;
	}

	@javax.persistence.Column(name="SMTPUserName",length=50)
	private String smtpusername = "";

	public void setSmtpusername(String smtpusername) {
		this.smtpusername = smtpusername;
	}

	public String getSmtpusername() {
		return smtpusername;
	}

	@javax.persistence.Column(name="Server",length=50)
	private String server = "";

	public void setServer(String server) {
		this.server = server;
	}

	public String getServer() {
		return server;
	}

	@javax.persistence.Column(name="UserGroup",length=50)
	private String usergroup;

	public void setUsergroup(String usergroup) {
		this.usergroup = usergroup;
	}

	public String getUsergroup() {
		return usergroup;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empcode == null) ? 0 : empcode.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (empcode == null) {
			if (other.getEmpcode() != null)
				return false;
		} else if (!empcode.equals(other.getEmpcode()))
			return false;
		return true;
	}

	
	@Override
	public String toString() {
		return "User [id=" + id + ", address=" + address + ", dob=" + dob + ", designation=" + designation + ", empcode=" + empcode + ", empname=" + empname + ", loginname=" + loginname + ", loginpassword=" + loginpassword + ", phone=" + phone + ", port=" + port + ", smtppassword=" + smtppassword
				+ ", smtpusername=" + smtpusername + ", server=" + server + ", usergroup=" + usergroup + "]";
	}




	// <- Generated by DB Importer
}