package com.oes.model.my_sql.entities;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="user_group")
public class Usergroup {
	@EmbeddedId()
	private Key key = new Key();
	
	public long getGroupid() {
		return key.groupid;
	}
	
	public void setGroupid(long groupid) {
		key.groupid = groupid;
	}
	
	public long getUserid() {
		return key.userid;
	}

	public void setUserid(long userid) {
		key.userid = userid;
	}
	
	@Embeddable
	private static class Key implements Serializable{
		@javax.persistence.Column(name="groupId",length=11,nullable=false)
		long groupid;
		
		@javax.persistence.Column(name="userId",length=11,nullable=false)
		long userid;

	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Usergroup [groupid =" + getGroupid() + ", userid =" + getUserid() + "]";
	}
	
}