package com.oes.model.my_sql.entities;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="warehouse")
public class Warehouse {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="WareHouseID",length=10,nullable=false)
  private int warehouseid;

  public void setWarehouseid(int warehouseid) {
    this.warehouseid = warehouseid;
  }

  public int getWarehouseid() {
    return warehouseid;
  }

  @javax.persistence.Column(name="Name",length=45)
  private String name;

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  @javax.persistence.Column(name="address",length=150)
  private String address;

  public void setAddress(String address) {
    this.address = address;
  }

  public String getAddress() {
    return address;
  }
// <- Generated by DB Importer
}