package com.oes.model.my_sql.entities;

// Generated by DB Importer ->

@javax.persistence.Entity
@javax.persistence.Table(name="zipcodes")
public class Zipcodes {
  @javax.persistence.Id
  @javax.persistence.Column(name="ZipCode",length=15,nullable=false)
  private String zipcode;

  public void setZipcode(String zipcode) {
    this.zipcode = zipcode;
  }

  public String getZipcode() {
    return zipcode;
  }

  @javax.persistence.Column(name="City",length=30)
  private String city;

  public void setCity(String city) {
    this.city = city;
  }

  public String getCity() {
    return city;
  }

  @javax.persistence.Column(name="State",length=50)
  private String state;

  public void setState(String state) {
    this.state = state;
  }

  public String getState() {
    return state;
  }

  @javax.persistence.Column(name="type",length=20)
  private String type;

  public void setType(String type) {
    this.type = type;
  }

  public String getType() {
    return type;
  }
  
  @javax.persistence.Column(name="county",length=50)
  private String county;

  public void setCounty(String county) {
    this.county = county;
  }

  public String getCounty() {
    return county;
  }
  
  @javax.persistence.Column(name="areacode",length=10)
  private String areacode;

  public void setAreacode(String areacode) {
    this.areacode = areacode;
  }

  public String getAreacode() {
    return areacode;
  }
  
  @javax.persistence.Column(name="latitude",length=10)
  private String latitude;

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public String getLatitude() {
    return latitude;
  }
  
  @javax.persistence.Column(name="longitude",length=10)
  private String longitude;

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public String getLongitude() {
    return longitude;
  }

  @Override
  public String toString() {
	return "Zipcodes [zipcode=" + zipcode + ", city=" + city + ", state="
			+ state + ", type=" + type + ", county=" + county + ", areacode="
			+ areacode + ", latitude=" + latitude + ", longitude=" + longitude
			+ "]";
  }
  
}